/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ContactId = bigint;
export interface ContactSubmission {
  'id' : ContactId,
  'name' : string,
  'createdAt' : Timestamp,
  'email' : string,
  'message' : string,
}
export interface CreateContactArgs {
  'name' : string,
  'email' : string,
  'message' : string,
}
export interface CreateProductArgs {
  'imageUrls' : Array<string>,
  'name' : string,
  'description' : string,
  'sizes' : Array<string>,
  'category' : string,
  'colors' : Array<string>,
  'price' : bigint,
}
export interface Product {
  'id' : ProductId,
  'imageUrls' : Array<string>,
  'name' : string,
  'createdAt' : Timestamp,
  'description' : string,
  'isActive' : boolean,
  'sizes' : Array<string>,
  'updatedAt' : Timestamp,
  'category' : string,
  'colors' : Array<string>,
  'price' : bigint,
}
export type ProductId = bigint;
export type Timestamp = bigint;
export interface UpdateProductArgs {
  'id' : ProductId,
  'imageUrls' : Array<string>,
  'name' : string,
  'description' : string,
  'sizes' : Array<string>,
  'category' : string,
  'colors' : Array<string>,
  'price' : bigint,
}
export interface _SERVICE {
  'addProduct' : ActorMethod<[CreateProductArgs], Product>,
  'deleteProduct' : ActorMethod<[ProductId], boolean>,
  'getActiveProducts' : ActorMethod<[], Array<Product>>,
  'getAdmin' : ActorMethod<[], Principal>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getContactSubmissions' : ActorMethod<[], Array<ContactSubmission>>,
  'getProductById' : ActorMethod<[ProductId], [] | [Product]>,
  'getProductsByCategory' : ActorMethod<[string], Array<Product>>,
  'initialize' : ActorMethod<[], undefined>,
  'submitContact' : ActorMethod<[CreateContactArgs], ContactSubmission>,
  'toggleProductActive' : ActorMethod<[ProductId], [] | [Product]>,
  'updateProduct' : ActorMethod<[UpdateProductArgs], [] | [Product]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];